package com.policyboss.policybosspro.core.response.master.userConstant

import com.webengage.sdk.android.utils.http.Response

data class UserConstantResponse(
    val MasterData: UserConstantEntity?,
    val Message: String,
    val Status: String,
    val StatusNo: Int
)

data class UserConstantEntity(
    val CVUrl: String? = null,
    //val ERPID: Int,
    val EliteKotakUrl: String? = null,
    val FBAId:  String? = null,
    val FourWheelerEnabled: String? = null,
    val FourWheelerUrl: String? = null,
    val HealthDemoUrl: String? = null,
    val HealthPopup: String? = null,
    val InvestmentEnabled: String? = null,
    val InvestmentUrl: String? = null,
    val IsDynamicDashEnabled: String? = null,
    val LeadDashUrl: String? = null,
    val ManagName: String? = null,
    val MangEmail: String? = null,
    val MangMobile: String? = null,
    val PBByCrnSearch: String? = null,
    val POSPNo: String? = null,
    val RaiseTickitEnabled: String? = null,
    val RaiseTickitUrl: String? = null,
    val SuppEmail: String? = null,
    val SuppMobile: String? = null,
    val TermPopup: String? = null,
    val TermPopupurl: String? = null,
    val TwoWheelerEnabled: String? = null,
    val TwoWheelerUrl: String? = null,
    val androidpromarkefbaurl: String? = null,
    val androidpromarketEnable: String? = null,
    val androidpromarketuidurl: String? = null,
    val androidproouathEnabled: String? = null,
    val androidproversion: String? = null,
    //val crnmobileno: String? = null,
    val dashboardarray: List<Dashboardarray>,
    val enablesynccontact: String? = null,
    val enablesyncprofileupdate: String? = null,
    val hdfc_code: String? = null,
    val healthurl: String? = null,
    val healthurltemp: String? = null,
    val insurancerepositorylink: String? = null,
    val iosuid:  String? = null,
    val iosversion: String? = null,
    val messagesender: String? = null,
    val myaccountupdateurl: String? = null,
    val notif_popupurl_elite: String? = null,
    val notificationpopupurl: String? = null,
    val pospselfdesignation: String? = null,
    val pospselfphoto: String? = null,
    val serviceurl: String? = null,
    val uid:  String? = null,
    val enable_pro_Addsubuser_url : String? = null
)