package com.policyboss.policybosspro.core.response.master.userConstant

import com.webengage.sdk.android.utils.http.Response

data class UserConstantResponse(
    val MasterData: UserConstantEntity?,
    val Message: String,
    val Status: String,
    val StatusNo: Int
)

data class UserConstantEntity(
    val CVUrl: String,
    val ERPID: Int,
    val EliteKotakUrl: String,
    val FBAId: Int,
    val FourWheelerEnabled: String,
    val FourWheelerUrl: String,
    val HealthDemoUrl: String,
    val HealthPopup: String,
    val InvestmentEnabled: String,
    val InvestmentUrl: String,
    val IsDynamicDashEnabled: String,
    val LeadDashUrl: String,
    val ManagName: String,
    val MangEmail: String,
    val MangMobile: String,
    val PBByCrnSearch: String,
    val POSPNo: Int,
    val RaiseTickitEnabled: String,
    val RaiseTickitUrl: String,
    val SuppEmail: String,
    val SuppMobile: String,
    val TermPopup: String,
    val TermPopupurl: String,
    val TwoWheelerEnabled: String,
    val TwoWheelerUrl: String,
    val androidpromarkefbaurl: String,
    val androidpromarketEnable: String,
    val androidpromarketuidurl: String,
    val androidproouathEnabled: String,
    val androidproversion: String,
    val crnmobileno: Long,
    val dashboardarray: List<Dashboardarray>,
    val enablesynccontact: String,
    val enablesyncprofileupdate: String,
    val hdfc_code: String,
    val healthurl: String,
    val healthurltemp: String,
    val insurancerepositorylink: String,
    val iosuid: Int,
    val iosversion: String,
    val messagesender: String,
    val myaccountupdateurl: String,
    val notif_popupurl_elite: String,
    val notificationpopupurl: String,
    val pospselfdesignation: String,
    val pospselfphoto: String,
    val serviceurl: String,
    val uid: Int,
    val enable_pro_Addsubuser_url : String? = null
)