package com.policyboss.policybosspro.core.response.profile

import com.policyboss.policybosspro.core.response.APIResponse

data class MyAcctDtlResponse(
    val MasterData: List<AccountDtlEntity>,

): APIResponse()

data class AccountDtlEntity(
    val Address_1: String? = null,
    val Address_2: String? = null,
    val Address_3: String? = null,
    val Amount: String? = null,
    val City: String? = null,
    val CityId: String? = null,
    val CreaOn: String? = null,
    val CustID: String? = null,
    val DOB: String? = null,
    val Designation: String? = null,
    val DisplayDesignation: String? = null,
    val DisplayEmail: String? = null,
    val DisplayPhoneNo: String? = null,
    val EditEmailId: String? = null,
    val EditMobiNumb: String? = null,
    val EmailID: String? = null,
    val FBACode: String? = null,
    val FBAID: String? = null,
    val FBAPan: String? = null,
    val FBARID: String? = null,
    val FBAStat: String? = null,
    val FBAType: String? = null,
    val FirstName: String? = null,
    val FullName: String? = null,
    val Gender: String? = null,
    val GstNo: String? = null,
    val IntrCode: String? = null,
    val IntrType: String? = null,
    val IsBlocked: String? = null,
    val IsCustIdRequ: String? = null,
    val IsFoc: String? = null,
    val JoinDate: String? = null,
    val LastName: String? = null,
    val LeadID: String? = null,
    val LoanID: String? = null,
    val LoanName: String? = null,
    val LoanStat: String? = null,
    val Loan_Aadhaar: String? = null,
    val Loan_Account_Type: String? = null,
    val Loan_BankAcNo: String? = null,
    val Loan_BankBranch: String? = null,
    val Loan_BankCity: String? = null,
    val Loan_BankName: String? = null,
    val Loan_IFSC: String? = null,
    val Loan_MICR: String? = null,
    val Loan_PAN: String? = null,
    val MiddName: String? = null,
    val Mobile_1: String? = null,
    val Mobile_2: String? = null,
    val OtheName: String? = null,
    val Other_Aadhaar: String? = null,
    val Other_Account_Type: String? = null,
    val Other_BankAcNo: String? = null,
    val Other_BankBranch: String? = null,
    val Other_BankName: String? = null,
    val Other_IFSC: String? = null,
    val Other_MICR: String? = null,
    val Other_PAN: String? = null,
    val POSPCode: String? = null,
    val POSPFrom: String? = null,
    val POSPName: String? = null,
    val POSPNo: String? = null,
    val POSPRegiDate: String? = null,
    val POSPStat: String? = null,
    val PaidDate: String? = null,
    val PayStat: String? = null,
    val PinCode: String? = null,
    val Posp_Aadhaar: String? = null,
    val Posp_Account_Type: String? = null,
    val Posp_Address1: String? = null,
    val Posp_Address2: String? = null,
    val Posp_Address3: String? = null,
    val Posp_BankAcNo: String? = null,
    val Posp_BankBranch: String? = null,
    val Posp_BankName: String? = null,
    val Posp_ChanPartCode: String? = null,
    val Posp_City: String? = null,
    val Posp_DOB: String? = null,
    val Posp_Email: String? = null,
    val Posp_Gender: String? = null,
    val Posp_IFSC: String? = null,
    val Posp_MICR: String? = null,
    val Posp_Mobile1: String? = null,
    val Posp_Mobile2: String? = null,
    val Posp_PAN: String? = null,
    val Posp_PinCode: String? = null,
    val Posp_ServiceTaxNo: String? = null,
    val Posp_StatID: String? = null,
    val ProdID: String? = null,
    val ProfPictName: String? = null,
    val Remarks: String? = null,
    val RewaPoin: String? = null,
    val SMID: String? = null,
    val StatDate: String? = null,
    val StateName: String? = null,
    val SuppAgenId: String? = null,
    val created_by: String? = null,
    val created_on: String? = null,
    val doc_available: List<DocAvailable>,
    val salescode: String? = null
)

data class DocAvailable(
    val DocName: String? = null,
    val DocType: Int = 0,
    val FileName: String? = null
)